### ISSUE TITLE
streaming.htmlの最後

### ISSUE THREAD

**Issue by chikina-dev** [mackerel-misogi/camFesOmiya2022#31]
div class=main
の部分閉じてない影響かわかりませんがフッターがメインに含まれてます
これって仕様です？
画像写ってれば良いけど
<img width="1302" alt="スクリーンショット 2022-12-04 11 41 35" src="https://user-images.githubusercontent.com/107536212/205471482-219201e9-7989-4f8d-82d7-75d573cc9b78.png">

**Comment by AyaExpTech** [comment]
669dffaaad68ce715bd5851f80eb28a24fb63afa
1c0171666be5a6380d7180c0a3f09ed78f0e7812

仕様じゃないので直しておきました
そもそも閉じてないのでHTMLの仕様違反ですね……
